# Generated by Django 5.2.8 on 2026-08-10 19:25

import the_music_tree_genre_kit.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', the_music_tree_genre_kit.field.AppCharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Criteria Type',
                'verbose_name_plural': 'Criteria Types',
                'constraints': [models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='criteria_non_empty_label')],
            },
        ),
    ]
