# Generated by Django 5.2.8 on 2026-08-21 18:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_music_tree_genre_kit', '0001_initial'),
        migrations.swappable_dependency(settings.ARTIST_MODEL),
        migrations.swappable_dependency(settings.ALBUM_MODEL),
        migrations.swappable_dependency(settings.CRITERIA_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('title', the_music_tree_api_kit.field.AppCharField(max_length=256)),
                ('track_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('language', the_music_tree_api_kit.field.AppCharField(blank=True, default=None, max_length=3, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('album', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_of_album', to=settings.ALBUM_MODEL)),
                ('artists', the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='tracks_of_artist', to=settings.ARTIST_MODEL)),
                ('genre', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks_of_criteria', to=settings.CRITERIA_MODEL)),
            ],
        ),
    ]
