# Generated by Django 5.2.8 on 2026-08-21 18:46

import django.db.models.deletion
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0003_track_album_user_artist_user_album_album_artists_and_more'),
        ('the_music_tree_genre_kit', '0002_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(related_name='tracks_of_playlist', through='fixture_app.TrackPlaylistRel', to='fixture_app.playlist'),
        ),
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['user', 'title'], name='the_music_t_user_id_db716d_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['user', 'genre'], name='the_music_t_user_id_f3e6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['user', 'album'], name='the_music_t_user_id_43a3cf_idx'),
        ),
    ]
