# Generated by Django 5.2.8 on 2026-08-22 18:34

import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_music_tree_genre_kit', '0004_playlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPlaylistRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('playlist', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='the_music_tree_genre_kit.playlist')),
                ('track', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='the_music_tree_genre_kit.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'the_music_tree_genre_kit_track_playlist_rel',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(related_name='tracks_of_playlist', through='the_music_tree_genre_kit.TrackPlaylistRel', to='the_music_tree_genre_kit.playlist'),
        ),
        migrations.AddIndex(
            model_name='trackplaylistrel',
            index=models.Index(fields=['user', 'playlist'], name='tpr_user_playlist_idx'),
        ),
        migrations.AddIndex(
            model_name='trackplaylistrel',
            index=models.Index(fields=['user', 'track'], name='tpr_user_track_idx'),
        ),
    ]
