# Generated by Django 5.2.8 on 2026-09-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_music_tree_genre_kit', '0007_importrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='archived',
        ),
    ]
