# Generated by Django 5.2.8 on 2026-10-08 17:46

import the_music_tree_api_kit.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_music_tree_genre_kit', '0009_trackplaylistrel_uniq_track_playlist_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='title',
            field=the_music_tree_api_kit.field.AppCharField(max_length=2048),
        ),
    ]
