class Fields:
    NAME_PUBLIC = "name"
    PARENT = "parent"
    CHILDREN = "children"
    TREE = "tree"
    SIDE = "side"
    ID = "id"
    TREE_NAME = "tree_name"
    PRIMARY_PARENTS = "primary_parents"
    SECONDARY_PARENTS = "secondary_parents"
    IS_UNACCEPTED_ROOT = "is_unaccepted_root"
