class Fields:
    NAME_PUBLIC = "name"
    PARENT = "parent"
    CHILDREN = "children"
    TREE = "tree"
    SIDE = "side"
    ID = "id"
    ALLOWS_MULTIPLE_PRIMARY_PARENTS = "allows_multiple_primary_parents"
    PRIMARY_PARENTS = "primary_parents"
    SECONDARY_PARENTS = "secondary_parents"
