# Generated by Django 5.2.8 on 2026-08-21 19:38

import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.AppForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_music_tree_genre_kit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('album_artists', the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='albums', to='fixture_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('_name', the_music_tree_api_kit.field.AppCharField(db_column='name', max_length=255)),
                ('parent', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fixture_app.criteria')),
                ('root', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descendants', to='fixture_app.criteria')),
                ('type', the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_music_tree_genre_kit.criteriatype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaLineageRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('degree', models.PositiveIntegerField()),
                ('ascendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendants_rels', to='fixture_app.criteria')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascendants_rels', to='fixture_app.criteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='ascendants',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(through='fixture_app.CriteriaLineageRel', through_fields=('descendant', 'ascendant'), to='fixture_app.criteria'),
        ),
        migrations.CreateModel(
            name='CriteriaPlaylist',
            fields=[
                ('playlist', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='criteria_playlist', serialize=False, to='fixture_app.playlist')),
            ],
            bases=('fixture_app.playlist', models.Model),
        ),
        migrations.AddConstraint(
            model_name='criteria',
            constraint=models.CheckConstraint(condition=models.Q(('_name', ''), _negated=True), name='non_empty_name'),
        ),
        migrations.AddConstraint(
            model_name='criteria',
            constraint=models.UniqueConstraint(fields=('_name', 'user'), name='unique_name_per_user'),
        ),
        migrations.AddField(
            model_name='criteriaplaylist',
            name='criteria',
            field=the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria_playlist', to='fixture_app.criteria'),
        ),
        migrations.AddField(
            model_name='criteriaplaylist',
            name='parent',
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fixture_app.criteriaplaylist'),
        ),
        migrations.AddField(
            model_name='criteriaplaylist',
            name='root',
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_descendants', to='fixture_app.criteriaplaylist'),
        ),
        migrations.AddField(
            model_name='criteriaplaylist',
            name='type',
            field=the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_music_tree_genre_kit.criteriatype'),
        ),
    ]
