# Generated by Django 5.2.8 on 2026-08-21 19:38

import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0001_initial'),
        ('the_music_tree_genre_kit', '0002_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fixture_track', serialize=False, to='the_music_tree_genre_kit.track')),
            ],
            bases=('the_music_tree_genre_kit.track',),
        ),
        migrations.CreateModel(
            name='TrackPlaylistRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('playlist', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='fixture_app.playlist')),
                ('track', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='the_music_tree_genre_kit.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
