# Generated by Django 5.2.8 on 2026-08-21 18:46

import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field.foreign_key.AppForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0002_album_artist_playlist'),
        ('the_music_tree_genre_kit', '0002_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fixture_track', serialize=False, to='the_music_tree_genre_kit.track')),
            ],
            bases=('the_music_tree_genre_kit.track',),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='album_artists',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='albums', to='fixture_app.artist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrackPlaylistRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('playlist', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='fixture_app.playlist')),
                ('track', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='the_music_tree_genre_kit.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaPlaylist',
            fields=[
                ('playlist', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='criteria_playlist', serialize=False, to='fixture_app.playlist')),
                ('criteria', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria_playlist', to='fixture_app.criteria')),
                ('parent', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fixture_app.criteriaplaylist')),
                ('root', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_descendants', to='fixture_app.criteriaplaylist')),
                ('type', the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_music_tree_genre_kit.criteriatype')),
            ],
            bases=('fixture_app.playlist', models.Model),
        ),
    ]
