# Generated by Django 5.2.8 on 2026-08-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0002_playlist_track_trackplaylistrel_criteriaplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='fixture_app.criteria'),
        ),
    ]
