# Generated by Django 5.2.8 on 2026-08-22 09:16, hand-edited: see repoint_criteria_playlist_bases docstring.

import django.db.models.deletion
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.AppForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Re-points fixture_app's ManualPlaylist/CriteriaPlaylist/TrackPlaylistRel at the kit's
    now-concrete Playlist and drops fixture_app's own local Playlist table.

    CriteriaPlaylist's MTI base changes from fixture_app.Playlist to
    the_music_tree_genre_kit.Playlist. A plain AlterField on the `playlist` OneToOne only
    updates the database-level FK target -- it never updates the migration state's
    recorded `bases=`, so Django would keep expecting an implicit parent link into a
    now-deleted fixture_app.Playlist. The DeleteModel+CreateModel pair inside
    state_operations below re-declares CriteriaPlaylist with the correct bases while
    database_operations only performs the actual (harmless, no data in this test-only
    fixture app) column-target change -- same technique as
    grow/migrations/0006_move_track_to_genre_kit.py's repoint_track_parent_link.

    fixture_app_criteriaplaylist also carries a pre-existing, state-untracked
    "playlist_ptr_id" column (drift predating this migration, still FK'd to
    fixture_app_playlist) that SQLite's FK-constraint validation trips over once
    fixture_app_playlist is dropped below, even though no code ever reads/writes
    it. SQLite refuses a plain `ALTER TABLE ... DROP COLUMN` on it because it
    carries a UNIQUE constraint, so drop_stale_playlist_ptr_column below rebuilds
    the table by hand (Django's state has no field to RemoveField from, so this
    can't go through schema_editor's normal field-driven remake).
    """

    def drop_stale_playlist_ptr_column(apps, schema_editor):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TABLE "fixture_app_criteriaplaylist" RENAME TO "_fixture_app_criteriaplaylist_old"')
            cursor.execute(
                'CREATE TABLE "fixture_app_criteriaplaylist" ('
                '"playlist_id" char(32) NOT NULL PRIMARY KEY REFERENCES "the_music_tree_genre_kit_playlist" ("uuid") DEFERRABLE INITIALLY DEFERRED, '
                '"criteria_id" char(32) NULL UNIQUE REFERENCES "fixture_app_criteria" ("uuid") DEFERRABLE INITIALLY DEFERRED, '
                '"type_id" bigint NOT NULL REFERENCES "the_music_tree_genre_kit_criteriatype" ("id") DEFERRABLE INITIALLY DEFERRED, '
                '"parent_id" char(32) NULL REFERENCES "fixture_app_criteriaplaylist" ("playlist_id") DEFERRABLE INITIALLY DEFERRED, '
                '"root_id" char(32) NOT NULL REFERENCES "fixture_app_criteriaplaylist" ("playlist_id") DEFERRABLE INITIALLY DEFERRED'
                ")"
            )
            cursor.execute(
                'INSERT INTO "fixture_app_criteriaplaylist" ("playlist_id", "criteria_id", "type_id", "parent_id", "root_id") '
                'SELECT "playlist_id", "criteria_id", "type_id", "parent_id", "root_id" FROM "_fixture_app_criteriaplaylist_old"'
            )
            cursor.execute('DROP TABLE "_fixture_app_criteriaplaylist_old"')
            cursor.execute(
                'CREATE INDEX "fixture_app_criteriaplaylist_type_id_eaa1f49c" ON "fixture_app_criteriaplaylist" ("type_id")'
            )
            cursor.execute(
                'CREATE INDEX "fixture_app_criteriaplaylist_parent_id_a7978713" ON "fixture_app_criteriaplaylist" ("parent_id")'
            )
            cursor.execute(
                'CREATE INDEX "fixture_app_criteriaplaylist_root_id_a6b30045" ON "fixture_app_criteriaplaylist" ("root_id")'
            )

    dependencies = [
        ('fixture_app', '0002_track_trackplaylistrel'),
        ('the_music_tree_genre_kit', '0004_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPlaylist',
            fields=[
                ('_name', the_music_tree_api_kit.field.AppCharField(db_column='name', max_length=255)),
                ('playlist', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='manual_playlist', serialize=False, to='the_music_tree_genre_kit.playlist')),
            ],
            bases=('the_music_tree_genre_kit.playlist', models.Model),
        ),
        migrations.AlterField(
            model_name='trackplaylistrel',
            name='playlist',
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_playlist_rels', to='the_music_tree_genre_kit.playlist'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='criteriaplaylist',
                    name='playlist',
                    field=the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='criteria_playlist', serialize=False, to='the_music_tree_genre_kit.playlist'),
                ),
            ],
            state_operations=[
                migrations.DeleteModel(name='CriteriaPlaylist'),
                migrations.CreateModel(
                    name='CriteriaPlaylist',
                    fields=[
                        ('playlist', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='criteria_playlist', serialize=False, to='the_music_tree_genre_kit.playlist')),
                        ('criteria', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria_playlist', to='fixture_app.criteria')),
                        ('parent', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fixture_app.criteriaplaylist')),
                        ('root', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_descendants', to='fixture_app.criteriaplaylist')),
                        ('type', the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_music_tree_genre_kit.criteriatype')),
                    ],
                    bases=('the_music_tree_genre_kit.playlist', models.Model),
                ),
            ],
        ),
        migrations.RunPython(drop_stale_playlist_ptr_column, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
