# Generated by Django 5.2.8 on 2026-08-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0003_manualplaylist_alter_trackplaylistrel_playlist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackPlaylistRel',
        ),
    ]
