# Generated by Django 5.2.8 on 2026-08-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0004_delete_trackplaylistrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='side',
            field=models.CharField(blank=True, choices=[('core', 'Core'), ('pop', 'Pop')], db_column='side', max_length=4, null=True),
        ),
    ]
