# Generated by Django 5.2.8 on 2026-08-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0005_criteria_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
