# Generated by Django 5.2.8 on 2026-08-31 07:27

import the_music_tree_api_kit.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0006_track_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='side',
            field=the_music_tree_api_kit.field.AppCharField(blank=True, choices=[('core', 'Core'), ('pop', 'Pop')], db_column='side', max_length=4, null=True),
        ),
    ]
