# Generated by Django 5.2.8 on 2026-08-31 15:50

import django.db.models.deletion
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0007_alter_criteria_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='side',
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('side', the_music_tree_api_kit.field.AppCharField(blank=True, choices=[('core', 'Core'), ('pop', 'Pop')], db_column='side', max_length=4, null=True)),
                ('criteria_ptr', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genre', serialize=False, to='fixture_app.criteria')),
            ],
            bases=('fixture_app.criteria', models.Model),
        ),
    ]
