# Generated by Django 5.2.8 on 2026-09-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0008_remove_criteria_side_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='summary',
            field=models.TextField(blank=True, db_column='summary', null=True),
        ),
    ]
