# Generated by Django 5.2.8 on 2026-09-18 08:40

import the_music_tree_api_kit.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0009_criteria_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='wikidata_id',
            field=the_music_tree_api_kit.field.AppCharField(blank=True, db_column='wikidata_id', max_length=32, null=True),
        ),
    ]
