# Generated by Django 5.2.8 on 2026-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0010_genre_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
