# Generated by Django 5.2.8 on 2026-09-25 14:22

import django.db.models.deletion
import django.db.models.functions.text
import the_music_tree_api_kit.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0011_genre_is_excluded_genre_is_manually_edited_and_more'),
        ('the_music_tree_genre_kit', '0007_importrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='criteria',
            name='unique_name_per_user',
        ),
        migrations.AddField(
            model_name='genre',
            name='last_seen_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='the_music_tree_genre_kit.importrun'),
        ),
        migrations.AddField(
            model_name='genre',
            name='source',
            field=the_music_tree_api_kit.field.AppCharField(choices=[('pipeline', 'Pipeline'), ('app', 'App'), ('admin', 'Admin')], default='app', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='criteria',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('_name'), models.F('user'), name='unique_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(condition=models.Q(('wikidata_id__isnull', False)), fields=('wikidata_id', 'user'), name='unique_wikidata_id_per_user'),
        ),
    ]
