# Generated by Django 5.2.8 on 2026-09-25 14:32

import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0012_remove_criteria_unique_name_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='additional_primary_parents',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='additional_primary_children', to='fixture_app.criteria'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='allows_multiple_primary_parents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criteria',
            name='secondary_parents',
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(blank=True, related_name='secondary_children', to='fixture_app.criteria'),
        ),
    ]
