# Generated by Django 5.2.8 on 2026-09-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0013_criteria_multiple_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='has_name_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
