# Generated by Django 5.2.8 on 2026-09-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0014_genre_has_name_conflict'),
    ]

    run_before = [("the_music_tree_genre_kit", "0008_remove_track_archived")]

    operations = [
        migrations.RemoveConstraint(
            model_name='genre',
            name='unique_wikidata_id_per_user',
        ),
    ]
