# Generated by Django 5.2.8 on 2026-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0016_genre_is_unaccepted_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='allows_multiple_primary_parents',
        ),
        migrations.AddField(
            model_name='criteria',
            name='tree_name',
            field=models.CharField(choices=[('canonical', 'Canonical'), ('regional', 'Regional')], default='canonical', max_length=16),
        ),
    ]
