# Generated by Django 5.2.8 on 2026-10-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0017_criteria_tree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='youtube_unplayable_reason',
            field=models.CharField(blank=True, choices=[('not_found', 'Not Found'), ('not_embeddable', 'Not Embeddable'), ('private', 'Private'), ('not_processed', 'Not Processed'), ('region_whitelisted', 'Region Whitelisted')], default=None, max_length=32, null=True),
        ),
    ]
