# Generated by Django 5.2.8 on 2026-10-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture_app', '0018_track_youtube_unplayable_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='musicbrainz_recording_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
